spring:
  r2dbc:
    username: root
    password: ""
    url: r2dbcs:mysql://localhost:3306/warehouse_test_2?serverZoneId=Asia/Shanghai
  redis:
    host: "localhost"
    port: 6379
    client-name: ${spring.application.name}
    client-type: lettuce #provide reactive connection
    date_format: "dd-MM-yyyy"
    time_format: "HH:mm:ss"

jwt:
  expiration:
    duration: 3600

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.ffzs.webflux: DEBUG  # 设置你的应用程序包的日志级别
  file:
    name: file.log  # 将日志输出到文件
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # 控制台输出格式
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"     # 文件输出格式
