services:
  zookeeper:
    image: zookeeper:3.7.0
    ports: ["2181:2181"]

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports: ["9092:9092"]
    depends_on: [zookeeper]
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181