spring:
  application:
    name: warehouse-client
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
        consumer:
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          properties:
            spring:
              json:
                value:
                  default:
                    type: com.snw.api.kafka.GoodsArrivedEvent, com.snw.api.kafka.UnloadingStartedEvent, com.snw.api.kafka.UnloadingCompletedEvent
                trusted:
                  packages: "*"
      bindings:
        prices-in-0:
          destination: warehouse.api.price
          group: dollarClientGroup

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

server:
  port: 8003